# Generated by Django 4.2.27 on 2026-02-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('REGULAR', 'Regular User'), ('STAFF', 'Staff Member'), ('CLIENT', 'Client Device'), ('ADMIN', 'Administrator')], db_index=True, default='REGULAR', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_clients', models.IntegerField(default=2, help_text='Maximum number of client devices allowed')),
                ('max_storage_gb', models.IntegerField(default=5, help_text='Maximum storage in GB')),
                ('can_use_cloud', models.BooleanField(default=False, help_text='Can upload to cloud storage')),
                ('active_clients_count', models.IntegerField(default=0, help_text='Number of active client devices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text="Friendly name for the device (e.g., 'Coffee Shop Main TV')", max_length=100)),
                ('device_identifier', models.CharField(blank=True, help_text='Hardware identifier or IP address', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False, help_text='Currently connected/playing')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('current_video_id', models.UUIDField(blank=True, help_text='Currently playing video', null=True)),
                ('playback_position', models.IntegerField(default=0, help_text='Current playback position in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Account',
                'verbose_name_plural': 'Client Accounts',
                'db_table': 'client_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='8-character alphanumeric code', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False, help_text='Has been activated by a client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_code', to='accounts.clientaccount')),
                ('staff', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Code',
                'verbose_name_plural': 'Access Codes',
                'db_table': 'access_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['staff', '-created_at'], name='client_acco_staff_i_1b550b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['is_online'], name='client_acco_is_onli_ee7503_idx'),
        ),
        migrations.AddIndex(
            model_name='accesscode',
            index=models.Index(fields=['staff', '-created_at'], name='access_code_staff_i_5c7fba_idx'),
        ),
        migrations.AddIndex(
            model_name='accesscode',
            index=models.Index(fields=['code'], name='access_code_code_447fe1_idx'),
        ),
    ]
