# Generated by Django 4.2.28 on 2026-02-03 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('storage_type', models.CharField(choices=[('LOCAL', 'Local Filesystem'), ('CLOUD', 'Cloud Storage')], default='LOCAL', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('cloud_url', models.URLField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('format', models.CharField(choices=[('mp4', 'MP4'), ('mkv', 'MKV'), ('webm', 'WebM')], default='mp4', max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='videos_owner_i_ff9025_idx'), models.Index(fields=['is_active'], name='videos_is_acti_f4f5cf_idx')],
            },
        ),
    ]
