# Generated by Django 4.2.27 on 2026-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Visible to all users'),
        ),
    ]
