# Generated by Django 4.2.27 on 2026-02-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_by_admin',
            field=models.BooleanField(default=False, help_text='Uploaded by admin, requires approval to delete'),
        ),
    ]
