# Generated by Django 4.2.27 on 2026-02-04 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_user_type_staffprofile_clientaccount_accesscode_and_more'),
        ('videos', '0004_videodeletionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffVideoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global_for_staff', models.BooleanField(default=False, help_text='Show to all clients of this staff')),
                ('play_order', models.IntegerField(default=0, help_text='Order in playlist (lower plays first)')),
                ('loop_enabled', models.BooleanField(default=True, help_text='Loop this video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Specific client. NULL if global for all staff clients', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_assignments', to='accounts.clientaccount')),
                ('staff', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_assignments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='videos.video')),
            ],
            options={
                'verbose_name': 'Staff Video Assignment',
                'verbose_name_plural': 'Staff Video Assignments',
                'db_table': 'staff_video_assignments',
                'ordering': ['play_order', '-created_at'],
                'indexes': [models.Index(fields=['staff', 'play_order'], name='staff_video_staff_i_3966b7_idx'), models.Index(fields=['assigned_to', 'play_order'], name='staff_video_assigne_3fe1b8_idx')],
                'unique_together': {('video', 'assigned_to')},
            },
        ),
    ]
