# Generated by Django 4.2.27 on 2026-02-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_staffvideoassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rotation',
            field=models.IntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0, help_text='Video rotation angle for display'),
        ),
    ]
