"""
Staff dashboard views.
"""

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.http import require_http_methods


@login_required
def staff_dashboard_view(request):
    """
    Main staff dashboard showing stats and quick actions.
    """
    # Ensure user is staff
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied. Staff members only.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import StaffProfile, AccessCode
    
    # Get or create staff profile
    staff_profile, created = StaffProfile.objects.get_or_create(
        user=request.user,
        defaults={
            'max_clients': 2,
            'max_storage_gb': 5,
            'can_use_cloud': False
        }
    )
    
    # Count available codes
    available_codes = staff_profile.get_available_slots()
    
    context = {
        'staff_profile': staff_profile,
        'available_codes': available_codes,
    }
    
    return render(request, 'dashboard/staff/dashboard.html', context)


@login_required
def staff_choose_plan_view(request):
    """
    Allow staff to choose/upgrade their subscription plan.
    """
    # Placeholder for now - will implement plan selection in Phase 4
    messages.info(request, 'Plan selection coming soon! Using free plan for now.')
    return redirect('staff_dashboard')


# =============================================================================
# Access Code Management
# =============================================================================

@login_required
def staff_codes_view(request):
    """
    Display all access codes generated by staff.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import StaffProfile, AccessCode
    
    staff_profile = get_object_or_404(StaffProfile, user=request.user)
    codes = AccessCode.objects.filter(staff=request.user).order_by('-created_at')
    
    # Calculate stats
    codes_count = codes.count()
    active_codes_count = codes.filter(is_active=True, is_used=False).count()
    used_codes_count = codes.filter(is_used=True).count()
    available_slots = staff_profile.get_available_slots()
    can_generate = staff_profile.can_generate_code()
    
    context = {
        'staff_profile': staff_profile,
        'codes': codes,
        'codes_count': codes_count,
        'active_codes_count': active_codes_count,
        'used_codes_count': used_codes_count,
        'available_slots': available_slots,
        'can_generate': can_generate,
    }
    
    return render(request, 'dashboard/staff/codes.html', context)


@login_required
@require_http_methods(["POST"])
def generate_code_view(request):
    """
    Generate a new access code for client.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import StaffProfile, AccessCode
    
    staff_profile = get_object_or_404(StaffProfile, user=request.user)
    
    # Check if can generate more codes
    if not staff_profile.can_generate_code():
        messages.error(request, 'You have reached your client limit. Please upgrade your plan.')
        return redirect('staff_codes')
    
    # Generate code
    code = AccessCode.generate_unique_code()
    access_code = AccessCode.objects.create(
        code=code,
        staff=request.user,
        is_active=True
    )
    
    messages.success(request, f'Access code generated: {access_code.code}')
    return redirect('staff_codes')


@login_required
@require_http_methods(["POST"])
def deactivate_code_view(request, code_id):
    """
    Deactivate an access code.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import AccessCode
    
    code = get_object_or_404(AccessCode, id=code_id, staff=request.user)
    
    if code.is_used:
        messages.error(request, 'Cannot deactivate a code that is already in use.')
    else:
        code.deactivate()
        messages.success(request, f'Access code {code.code} has been deactivated.')
    
    return redirect('staff_codes')


# =============================================================================
# Client Management
# =============================================================================

@login_required
def staff_clients_view(request):
    """
    Display all client devices connected to staff.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import ClientAccount
    
    clients = ClientAccount.objects.filter(staff=request.user).select_related('user', 'access_code').order_by('-created_at')
    
    # Calculate stats
    clients_count = clients.count()
    online_count = clients.filter(is_online=True).count()
    offline_count = clients_count - online_count
    
    context = {
        'clients': clients,
        'clients_count': clients_count,
        'online_count': online_count,
        'offline_count': offline_count,
    }
    
    return render(request, 'dashboard/staff/clients.html', context)


@login_required
@require_http_methods(["POST"])
def edit_client_view(request, client_id):
    """
    Edit client device details.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import ClientAccount
    
    client = get_object_or_404(ClientAccount, id=client_id, staff=request.user)
    
    device_name = request.POST.get('device_name', '').strip()
    
    if device_name:
        client.device_name = device_name
        client.save()
        messages.success(request, 'Client device updated successfully.')
    else:
        messages.error(request, 'Device name is required.')
    
    return redirect('staff_clients')


@login_required
@require_http_methods(["POST"])
def toggle_client_view(request, client_id):
    """
    Activate/deactivate a client device.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import ClientAccount
    
    client = get_object_or_404(ClientAccount, id=client_id, staff=request.user)
    
    client.is_active = not client.is_active
    client.save()
    
    status = 'activated' if client.is_active else 'deactivated'
    messages.success(request, f'Client device {client.device_name} has been {status}.')
    
    return redirect('staff_clients')


# =============================================================================
# Settings & Plans
# =============================================================================

@login_required
def staff_settings_view(request):
    """
    Staff settings page with account info and usage stats.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import StaffProfile, ClientAccount, AccessCode
    from apps.videos.models import Video
    
    staff_profile = get_object_or_404(StaffProfile, user=request.user)
    
    # Get stats
    clients_count = ClientAccount.objects.filter(staff=request.user).count()
    videos_count = Video.objects.filter(owner=request.user, is_active=True).count()
    codes_count = AccessCode.objects.filter(staff=request.user).count()
    
    context = {
        'staff_profile': staff_profile,
        'clients_count': clients_count,
        'videos_count': videos_count,
        'codes_count': codes_count,
    }
    
    return render(request, 'dashboard/staff/settings.html', context)


@login_required
def staff_plans_view(request):
    """
    Display available staff plans for upgrade.
    """
    if request.user.user_type != 'STAFF':
        messages.error(request, 'Access denied.')
        return redirect('choose_user_type')
    
    from apps.accounts.models import StaffProfile
    
    staff_profile = get_object_or_404(StaffProfile, user=request.user)
    
    context = {
        'staff_profile': staff_profile,
    }
    
    return render(request, 'dashboard/staff/plans.html', context)


# =============================================================================
# Account Type Switching
# =============================================================================

@login_required
@require_http_methods(["POST"])
def switch_account_type_view(request):
    """
    Switch between REGULAR and STAFF account types.
    """
    if not request.user.is_authenticated:
        messages.error(request, 'Please login first.')
        return redirect('login')
    
    new_type = request.POST.get('new_type')
    
    if new_type not in ['REGULAR', 'STAFF']:
        messages.error(request, 'Invalid account type.')
        return redirect('staff_settings')
    
    # Don't allow switching from CLIENT type
    if request.user.user_type == 'CLIENT':
        messages.error(request, 'Cannot switch account type for client accounts.')
        return redirect('client_player')
    
    # Don't allow admins to switch
    if request.user.is_admin:
        messages.error(request, 'Admin accounts cannot switch types.')
        return redirect('admin_dashboard')
    
    from apps.accounts.models import StaffProfile
    
    if new_type == 'STAFF':
        # Switch from REGULAR to STAFF
        if request.user.user_type == 'STAFF':
            messages.info(request, 'You are already a Staff member.')
            return redirect('staff_settings')
        
        request.user.user_type = 'STAFF'
        request.user.save()
        
        # Create staff profile if doesn't exist
        StaffProfile.objects.get_or_create(
            user=request.user,
            defaults={
                'max_clients': 2,
                'max_storage_gb': 5,
                'can_use_cloud': False
            }
        )
        
        messages.success(request, 'Account switched to Staff mode! You can now manage client devices.')
        return redirect('staff_dashboard')
    
    elif new_type == 'REGULAR':
        # Switch from STAFF to REGULAR
        if request.user.user_type != 'STAFF':
            messages.info(request, 'You are already a Regular user.')
            return redirect('user_dashboard')
        
        request.user.user_type = 'REGULAR'
        request.user.save()
        
        messages.success(request, 'Account switched to Regular user mode. Staff features have been disabled.')
        return redirect('user_dashboard')
    
    return redirect('staff_settings')
