# Generated by Django 4.2.27 on 2026-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_staff_plan',
            field=models.BooleanField(default=False, help_text='Is this a staff/business plan?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_clients',
            field=models.IntegerField(blank=True, help_text='Max client devices for staff plans. NULL for regular plans', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_storage_gb',
            field=models.IntegerField(blank=True, help_text='Max storage in GB for staff plans', null=True),
        ),
    ]
