# Generated by Django 4.2.28 on 2026-02-03 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('PLAN_CHANGED', 'Plan Changed'), ('VIDEO_DISABLED', 'Video Disabled'), ('VIDEO_DELETED', 'Video Deleted'), ('FEATURE_TOGGLED', 'Feature Toggled')], max_length=20)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_action_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='admin_actio_timesta_8b018d_idx'), models.Index(fields=['action_type'], name='admin_actio_action__8c6b47_idx')],
            },
        ),
    ]
