# Generated by Django 4.2.27 on 2026-02-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_adminactionlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_DELETED', 'User Deleted'), ('USER_BLOCKED', 'User Blocked'), ('PLAN_CHANGED', 'Plan Changed'), ('VIDEO_DISABLED', 'Video Disabled'), ('VIDEO_ACTIVATED', 'Video Activated'), ('VIDEO_ARCHIVED', 'Video Archived'), ('VIDEO_DELETED', 'Video Deleted'), ('FEATURE_TOGGLED', 'Feature Toggled'), ('DELETION_REQUESTED', 'Deletion Requested'), ('DELETION_APPROVED', 'Deletion Approved'), ('DELETION_REJECTED', 'Deletion Rejected')], max_length=20),
        ),
    ]
